source "https://rubygems.org"

ruby "3.2.2"

gem "sinatra", "~> 3.0"
gem "sinatra-contrib", "~> 3.0"
gem "puma", "~> 6.0"
gem "rack-cors"
gem "pg", "~> 1.5"
gem "sequel", "~> 5.0"
gem "json"
gem "rackup"
